### ISSUE TITLE
Kết nối ví và demo giao dịch

### ISSUE THREAD

**Issue by Phuong-Trang** [Phuong-Trang/se2022-14.1#13]

**Comment by quangthiennd15** [comment]
Mình đã tạo 1 smartcontract demo thử nghiệm đồng tiền theo tiêu chuẩn ERC20. Và khi dùng remixIDE thì mình cũng đã kết nối ví và thực hiện 1 số giao dịch để minh hoạ

**Comment by quangthiennd15** [comment]
Phần này thì mình đã demo giao dịch và tạo1 file readme trong folder token ae xem thử nhé!
