### ISSUE TITLE
Triển khai 1 smartcontract

### ISSUE THREAD

**Issue by quangthiennd15** [Phuong-Trang/se2022-14.1#3]
- Tìm hiểu về ngôn ngữ lập trình solidity
- Tìm hiểu về openzeppelin

**Comment by thuongmouse** [comment]
Mình có update trong file Solidity.md

**Comment by quangthiennd15** [comment]
Về lý thuyết thì Thương đã làm 1 file trong solidity. Mình đã tạo 1 contract ERC20.sol cũng là contract thử nghiệm của 1 đồng tiền theo tiêu chuân ERC20
